#Notes

##Why the Porsche cup is so DIFFICULT in iRacing

Even a good driver can find themselves several seconds off the pace in the porsche cup in iRacing. I've spent weeks driving this car competitively and I think I've FINALLY figured it out.

<intro music>

## Introduction
Driving the Porsche 911 GT3 Cup in iRacing can be a frustrating experience, especially when you're consistently several seconds off the pace. Even experienced drivers often struggle to find their rhythm in this car. It's unintuitive, lacks information in the force feedback, and forces you to rethink everything you love about driving. After spending weeks driving this car competitively, I've finally cracked the code. In this video, I'll share the key insights that will help you adapt to the Porsche 911 GT3 Cup and bring your lap times down. If you're impatient, skip to section 5, as it gives away all the secrets. But to prove that there's method to my madness, I'll explain why my findings make sense.

## 1. Differences to GT3
The Porsche cup has smaller tyres than the GT3, which means less grip and less corner exit. It also has much less aerodynamics, making the car less predictable, slower, and more difficult to drive. This is further compounded by the fact that the ABS and TC are less sophisticated than the GT3, but with similar power. The ABS is basic. These cars didn't always have ABS, and they were actually more intuitive to drive without it, albeit slower. Nowadays, when that basic ABS kicks in, especially while steering, you lose a lot of grip and time. The car doesn't really tell you anything about it and you're left to your own devices to pick up the pieces. And if that's not enough, these cars didn't have Traction Control in the past either, but now they do. The traction control is equally basic, and when it kicks in, it's crippling. Spins are almost unrecoverable. Even if you catch the slide, you're going to get swallowed up by the car behind you. If you're used to GT3, you'll be confused and discouraged by the way it punishes you for not knowing its secrets. Luckily, this video has the secrets.

## 2. Smooth Driving
Most modern rear wheel drive cars reward a certain amount of smoothness. The Porsche cup is no different, but it's much more sensitive to harsh inputs due to the characteristics we've already covered. The car is often used by professional GT3 drivers to find a driver's bad habits. Knowing ABS and TC limits, rotation amounts, corner speeds, braking points, alternative lines - all of these are made exponentially more difficult by the iRacing tyre model. And while I'm not here to complain about iRacing, it's important to understand that the tyre model is a key factor in making this car so difficult to drive. Because once you go over the limit, not only is it difficult to recover the car, but the car actually takes several corners, in some cases, to get back to full grip. And while iRacing extremists blame tyres overheating for this behaviour, it's not a true reflection of how a small slide recovers in real life. So smooth driving is key, even if that means under driving. 

## 3. Braking
This is where you'll find the biggest difference to the GT3. The Porsche cup cannot rely on complex aerodynamics to get the car pointed in the right direction. If you brake too hard, ABS kicks in and the tarmac turns to ice. If you brake too lightly, you'll end up braking way earlier, and the people who have already watched this video will outbrake you. They'll know you're never going to overtake them again because you're likely to just continue overdriving the car. Honestly, I felt like I was in jail when I first started driving this car. I'm normally towards the front of the grid, but I couldn't even scrape top 20 for weeks. Even when I examined the data on Garage61, I couldn't see how other people were braking the same amount as me but still managing to be faster. And braking is where I found the most time. I'll explain it in a later section, but right now, I have one more topic to cover, and it's an important one.

## 4. Balance
As alluded to, the weight is at the rear of the car. It's not mid-engined, it's rear-engined. So the engine sits right behind the rear wheels. This means the car is naturally prone to oversteer when off throttle and understeer when on throttle. It makes the car VERY sensitive to weight transfer and really emphasises what we talked about earlier when it comes to smooth driving. However, this also comes with some advantages, and that's what this video teaches you to exploit. You want to avoid turning while braking. You want to avoid turning while accelerating. Okay, that's a bit simplistic. You want to avoid hard braking while turning, and you want to avoid hard acceleration while turning. In other words, while turning, this car loves a bit of trail braking and a delicate gradual increase or decrease of throttle instead of an aggressive lift-off. It pays to know where the balance of the car is. As with every car, it's towards the front while braking and towards the rear while accelerating. That's why subtle inputs are so important for this car. To compound the issue, iRacing's force feedback doesn't communicate the car's balance well once you are over the limit. It accurately tells you what the front might feel like in the real car, but it doesn't make up for the lack of feedback at the rear, g-forces, and so on. As a result, it becomes a bit of a memory simulator, and driving this car is heavily based on memory. 

## 5. Solution
Ok, so what's the solution? Here are the golden rules for driving the Porsche Cup in iRacing:

1. Braking 60% vs braking 80% doesn't lose or gain you much time. It's all about downshifting as early as possible. The weight is on the rear of the car, so diff locking on downshift isn't a concern in this car.
2. Stay out of ABS and traction control while turning. Your car will get confused and will effectively shut down. While turning, never brake more than 30% and never accelerate more than 20% in this car.
3. Become aware of how much you can turn. If you come into a corner too quickly, you'll understeer before you even reach the apex. If you commit to too much throttle while turning, you'll understeer after the apex. 
4. Commit to your throttle once and once only. When you accelerate a lot, the front lifts and you lose steering ability. Be disciplined and wait for the right moment to pin the throttle. 
5. Embrace the rotation. Put your brake bias back a click or two if you're struggling to rotate the car. With weight over the rear, it's actually more difficult to spin this car than others, unless the traction control or ABS are active. But if you are over rotating in each corner, try to move the brake bias forward a click or two.
6. And finally, but this is iRacing specific, once you've locked or spun a wheel, iRacing can take several corners to fully recover grip. Under-driving this car makes you faster and helps the limited force feedback communicate what little the car tells you. 
7. Once you've mastered these things, all other driving rules apply and will come naturally. Good lines, use the space, apex correctly, carry speed, know the limits, etc. This car just tests your discipline. Those who drive LMP3 or V8 Supercars are likely to understand this car and the quirks of iRacing more than the average GT3 driver. 

## Summary
It's all very simple once you know, right? Well, I didn't. And it wasn't until my concerned PotatoNation community members realised my struggles and gave me pointers that the missing piece of the puzzle clicked into place. See, I was stubborn. I refused to have to memorize stupid little rules without understanding their reasons. For me, it was the aggressive and early downshift that made the difference. I hadn't even considered it. I was trying to be smooth under braking and changing gear when the car felt balanced, just before turn-in. Little did I realise, this was way too late for downshifting and it was compounding my issues. Once I started downshifting early and aggressively, the car felt much more balanced and predictable. Dare I say, enjoyable? I think that some people only love the Porsche Cup because they've figured out the secrets and love that others don't know them. However, I think that most drivers simply don't understand why they are quick and others struggle so much. I want this video to be a leveller. I want it to help everyone understand why this car is so difficult and how you can tame it.

I stream every Tuesday and Thursday at 9pm UK and Irish time. If this video helped you in any way, please consider subscribing or commenting. I'm Laurence, and I'll chat to you later